// 2026 世界杯 48 队详情数据
// 已确认大名单: 来源各队官方公告 (截至 2026-05-20)
// 其余标记 squadConfirmed: false

const teamDetails = {
  // ==================== A 组 ====================
  MEX: {
    fifaRank: 17, appearances: 18, best: '八强（1970、1986）',
    coach: '哈维尔·阿吉雷',
    keyPlayer: '埃德森·阿尔瓦雷斯（中场）',
    squadConfirmed: false,
    squad: [],
  },
  RSA: {
    fifaRank: 58, appearances: 4, best: '小组赛',
    coach: '雨果·布鲁斯',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },
  KOR: {
    fifaRank: 22, appearances: 12, best: '四强（2002）',
    coach: '洪明甫',
    keyPlayer: '孙兴慜（前锋）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '赵贤祐', no: 1 },
      { pos: '门将', name: '金承奎', no: 12 },
      { pos: '后卫', name: '金玟哉', no: 4 },
      { pos: '后卫', name: '薛英佑', no: 3 },
      { pos: '后卫', name: '金太焕', no: 2 },
      { pos: '中场', name: '李刚仁', no: 18 },
      { pos: '中场', name: '黄仁范', no: 6 },
      { pos: '中场', name: '黄喜灿', no: 11 },
      { pos: '中场', name: '李在城', no: 10 },
      { pos: '前锋', name: '孙兴慜', no: 7 },
      { pos: '前锋', name: '曹圭成', no: 9 },
    ],
  },
  CZE: {
    fifaRank: 39, appearances: 10, best: '亚军（1934、1962）',
    coach: '伊万·哈谢克',
    keyPlayer: '托马斯·绍切克（中场）',
    squadConfirmed: false,
    squad: [],
  },

  // ==================== B 组 ====================
  CAN: {
    fifaRank: 31, appearances: 3, best: '小组赛',
    coach: '杰西·马什',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },
  BIH: {
    fifaRank: 43, appearances: 2, best: '小组赛',
    coach: '萨沃·米洛舍维奇',
    keyPlayer: '埃丁·哲科（前锋）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '瓦西利', no: 1 },
      { pos: '后卫', name: '科拉希纳茨', no: 6 },
      { pos: '后卫', name: '德迪奇', no: 2 },
      { pos: '后卫', name: '哈兹卡杜尼奇', no: 5 },
      { pos: '后卫', name: '穆哈雷莫维奇', no: 4 },
      { pos: '中场', name: '哈兹亚赫梅托维奇', no: 8 },
      { pos: '中场', name: '巴希奇', no: 10 },
      { pos: '中场', name: '吉戈维奇', no: 14 },
      { pos: '中场', name: '巴吉拉塔雷维奇', no: 17 },
      { pos: '前锋', name: '哲科', no: 11 },
      { pos: '前锋', name: '德米罗维奇', no: 9 },
    ],
  },
  SUI: {
    fifaRank: 16, appearances: 13, best: '八强（1954）',
    coach: '穆拉特·亚金',
    keyPlayer: '扎卡（中场）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '科贝尔', no: 1 },
      { pos: '后卫', name: '阿坎吉', no: 4 },
      { pos: '后卫', name: '埃尔维迪', no: 5 },
      { pos: '后卫', name: '里卡多·罗德里格斯', no: 13 },
      { pos: '中场', name: '扎卡', no: 10 },
      { pos: '中场', name: '弗罗伊勒', no: 8 },
      { pos: '中场', name: '扎卡里亚', no: 6 },
      { pos: '中场', name: '贾沙里', no: 15 },
      { pos: '前锋', name: '恩博洛', no: 9 },
      { pos: '前锋', name: '奥卡福', no: 11 },
      { pos: '前锋', name: '恩多耶', no: 19 },
    ],
  },
  QAT: {
    fifaRank: 48, appearances: 2, best: '小组赛',
    coach: '洛佩特吉',
    keyPlayer: '阿克拉姆·阿菲夫（前锋）',
    squadConfirmed: false,
    squad: [],
  },

  // ==================== C 组 ====================
  BRA: {
    fifaRank: 3, appearances: 23, best: '冠军（1958、1962、1970、1994、2002）',
    coach: '安切洛蒂',
    keyPlayer: '维尼修斯（前锋）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '阿利松', no: 1 },
      { pos: '门将', name: '埃德森', no: 12 },
      { pos: '后卫', name: '马尔基尼奥斯', no: 4 },
      { pos: '后卫', name: '加布里埃尔', no: 3 },
      { pos: '后卫', name: '布雷默', no: 14 },
      { pos: '后卫', name: '达尼洛', no: 2 },
      { pos: '中场', name: '吉马良斯', no: 5 },
      { pos: '中场', name: '卡塞米罗', no: 8 },
      { pos: '中场', name: '帕奎塔', no: 10 },
      { pos: '前锋', name: '内马尔', no: 10 },
      { pos: '前锋', name: '维尼修斯', no: 7 },
    ],
  },
  MAR: {
    fifaRank: 13, appearances: 7, best: '四强（2022）',
    coach: '雷格拉吉',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },
  HAI: {
    fifaRank: 87, appearances: 2, best: '小组赛',
    coach: '米涅',
    keyPlayer: '伊西多尔（前锋）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '普拉西德', no: 1 },
      { pos: '后卫', name: '阿库斯', no: 2 },
      { pos: '后卫', name: '让-凯文·迪韦纳', no: 4 },
      { pos: '后卫', name: '里卡多·阿德', no: 5 },
      { pos: '中场', name: '贝勒加德', no: 8 },
      { pos: '中场', name: '丹利·让·雅克', no: 6 },
      { pos: '前锋', name: '威尔逊·伊西多尔', no: 9 },
      { pos: '前锋', name: '纳宗', no: 10 },
      { pos: '前锋', name: '皮埃罗', no: 11 },
      { pos: '前锋', name: '福琼', no: 7 },
      { pos: '前锋', name: '路易修斯·迪德森', no: 13 },
    ],
  },
  SCO: {
    fifaRank: 28, appearances: 9, best: '小组赛',
    coach: '史蒂夫·克拉克',
    keyPlayer: '安迪·罗伯逊（后卫）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '冈恩', no: 1 },
      { pos: '后卫', name: '罗伯逊', no: 3 },
      { pos: '后卫', name: '蒂尔尼', no: 6 },
      { pos: '后卫', name: '亨德利', no: 5 },
      { pos: '后卫', name: '希基', no: 2 },
      { pos: '中场', name: '麦克托米奈', no: 4 },
      { pos: '中场', name: '麦金', no: 7 },
      { pos: '中场', name: '麦格雷戈', no: 8 },
      { pos: '前锋', name: '亚当斯', no: 10 },
      { pos: '前锋', name: '戴克斯', no: 9 },
      { pos: '前锋', name: '克里斯蒂', no: 11 },
    ],
  },

  // ==================== D 组 ====================
  USA: {
    fifaRank: 12, appearances: 12, best: '四强（1930）',
    coach: '波切蒂诺',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },
  PAR: {
    fifaRank: 52, appearances: 9, best: '八强（2010）',
    coach: '丹尼尔·加内罗',
    keyPlayer: '米格尔·阿尔米隆（中场）',
    squadConfirmed: false,
    squad: [],
  },
  TUR: {
    fifaRank: 37, appearances: 3, best: '季军（2002）',
    coach: '蒙特拉',
    keyPlayer: '阿尔达·居莱尔（中场）',
    squadConfirmed: false,
    squad: [],
  },
  AUS: {
    fifaRank: 23, appearances: 7, best: '16 强（2006、2022）',
    coach: '托尼·波波维奇',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },

  // ==================== E 组 ====================
  GER: {
    fifaRank: 6, appearances: 21, best: '冠军（1954、1974、1990、2014）',
    coach: '纳格尔斯曼',
    keyPlayer: '穆西亚拉（中场）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '诺伊尔', no: 1 },
      { pos: '后卫', name: '基米希', no: 4 },
      { pos: '后卫', name: '吕迪格', no: 2 },
      { pos: '后卫', name: '施洛特贝克', no: 5 },
      { pos: '后卫', name: '约纳坦·塔', no: 6 },
      { pos: '中场', name: '维尔茨', no: 10 },
      { pos: '中场', name: '穆西亚拉', no: 12 },
      { pos: '中场', name: '格雷茨卡', no: 8 },
      { pos: '前锋', name: '哈弗茨', no: 9 },
      { pos: '前锋', name: '萨内', no: 11 },
      { pos: '前锋', name: '翁达夫', no: 13 },
    ],
  },
  ECU: {
    fifaRank: 30, appearances: 5, best: '16 强（2006）',
    coach: '贝卡塞塞',
    keyPlayer: '莫伊塞斯·凯塞多（中场）',
    squadConfirmed: false,
    squad: [],
  },
  CIV: {
    fifaRank: 41, appearances: 4, best: '小组赛',
    coach: '法埃',
    keyPlayer: '阿马德·迪亚洛（前锋）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '福法纳', no: 1 },
      { pos: '后卫', name: '科苏努', no: 2 },
      { pos: '后卫', name: '博利', no: 3 },
      { pos: '后卫', name: '迪奥曼德', no: 5 },
      { pos: '后卫', name: '柯南', no: 4 },
      { pos: '中场', name: '凯西', no: 8 },
      { pos: '中场', name: '福法纳', no: 6 },
      { pos: '中场', name: '阿马德·迪亚洛', no: 10 },
      { pos: '前锋', name: '佩佩', no: 19 },
      { pos: '前锋', name: '阿莱', no: 9 },
      { pos: '前锋', name: '库阿梅', no: 7 },
    ],
  },
  CUW: {
    fifaRank: 85, appearances: 1, best: '首次参赛',
    coach: '迪克·艾德沃卡特',
    keyPlayer: '巴佐尔（后卫）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '罗姆', no: 1 },
      { pos: '后卫', name: '巴佐尔', no: 4 },
      { pos: '后卫', name: '布雷内特', no: 2 },
      { pos: '后卫', name: '奥比斯波', no: 5 },
      { pos: '中场', name: '巴库纳', no: 8 },
      { pos: '中场', name: '科梅嫩西亚', no: 6 },
      { pos: '前锋', name: '钟塔西', no: 11 },
      { pos: '前锋', name: '桑杰·汉森', no: 9 },
      { pos: '前锋', name: '戈雷', no: 7 },
      { pos: '前锋', name: '卡斯塔内尔', no: 10 },
      { pos: '前锋', name: '洛卡迪亚', no: 19 },
    ],
  },

  // ==================== F 组 ====================
  NED: {
    fifaRank: 7, appearances: 12, best: '亚军（1974、1978、2010）',
    coach: '科曼',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },
  JPN: {
    fifaRank: 18, appearances: 8, best: '16 强（2002、2010、2022）',
    coach: '森保一',
    keyPlayer: '三笘薰（前锋）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '铃木彩艳', no: 1 },
      { pos: '后卫', name: '富安健洋', no: 16 },
      { pos: '后卫', name: '板仓滉', no: 4 },
      { pos: '后卫', name: '伊藤洋辉', no: 3 },
      { pos: '后卫', name: '菅原由势', no: 2 },
      { pos: '中场', name: '远藤航', no: 6 },
      { pos: '中场', name: '久保建英', no: 10 },
      { pos: '中场', name: '堂安律', no: 14 },
      { pos: '中场', name: '镰田大地', no: 8 },
      { pos: '前锋', name: '三笘薰', no: 7 },
      { pos: '前锋', name: '上田绮世', no: 9 },
    ],
  },
  TUN: {
    fifaRank: 36, appearances: 7, best: '小组赛',
    coach: '卡德里',
    keyPlayer: '汉尼拔·梅布里（中场）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '达门', no: 1 },
      { pos: '后卫', name: '塔勒比', no: 2 },
      { pos: '后卫', name: '梅里亚', no: 3 },
      { pos: '后卫', name: '布隆', no: 5 },
      { pos: '后卫', name: '阿卜迪', no: 4 },
      { pos: '中场', name: '斯希里', no: 6 },
      { pos: '中场', name: '梅布里', no: 10 },
      { pos: '中场', name: '本·苏莱曼', no: 8 },
      { pos: '前锋', name: '姆萨克尼', no: 7 },
      { pos: '前锋', name: '贾齐里', no: 9 },
      { pos: '前锋', name: '斯利蒂', no: 11 },
    ],
  },
  SWE: {
    fifaRank: 26, appearances: 13, best: '亚军（1958）',
    coach: '安德森',
    keyPlayer: '亚历山大·伊萨克（前锋）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '约翰松', no: 1 },
      { pos: '后卫', name: '林德洛夫', no: 3 },
      { pos: '后卫', name: '希恩', no: 4 },
      { pos: '后卫', name: '斯塔费尔特', no: 5 },
      { pos: '后卫', name: '霍尔姆', no: 2 },
      { pos: '中场', name: '贝里瓦尔', no: 8 },
      { pos: '中场', name: '斯万贝里', no: 6 },
      { pos: '中场', name: '阿亚里', no: 10 },
      { pos: '前锋', name: '伊萨克', no: 9 },
      { pos: '前锋', name: '吉厄克雷斯', no: 11 },
      { pos: '前锋', name: '埃兰加', no: 7 },
    ],
  },

  // ==================== G 组 ====================
  BEL: {
    fifaRank: 5, appearances: 15, best: '季军（2018）',
    coach: '特德斯科',
    keyPlayer: '凯文·德布劳内（中场）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '库尔图瓦', no: 1 },
      { pos: '后卫', name: '卡斯塔涅', no: 2 },
      { pos: '后卫', name: '德巴斯特', no: 4 },
      { pos: '后卫', name: '德温特', no: 3 },
      { pos: '后卫', name: '特阿特', no: 5 },
      { pos: '中场', name: '德布劳内', no: 7 },
      { pos: '中场', name: '奥纳纳', no: 6 },
      { pos: '中场', name: '蒂莱曼斯', no: 8 },
      { pos: '中场', name: '德凯特拉雷', no: 10 },
      { pos: '前锋', name: '卢卡库', no: 9 },
      { pos: '前锋', name: '多库', no: 11 },
    ],
  },
  IRN: {
    fifaRank: 21, appearances: 7, best: '小组赛',
    coach: '加莱诺埃',
    keyPlayer: '塔雷米（前锋）',
    squadConfirmed: false,
    squad: [],
  },
  EGY: {
    fifaRank: 32, appearances: 4, best: '小组赛',
    coach: '哈桑',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },
  NZL: {
    fifaRank: 94, appearances: 3, best: '小组赛',
    coach: '巴泽利',
    keyPlayer: '克里斯·伍德（前锋）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '马里诺维奇', no: 1 },
      { pos: '后卫', name: '史密斯', no: 2 },
      { pos: '后卫', name: '图伊洛马', no: 5 },
      { pos: '后卫', name: '皮纳克尔', no: 3 },
      { pos: '后卫', name: '凯凯利', no: 4 },
      { pos: '中场', name: '贝尔', no: 8 },
      { pos: '中场', name: '辛格', no: 10 },
      { pos: '中场', name: '罗哈斯', no: 7 },
      { pos: '前锋', name: '伍德', no: 9 },
      { pos: '前锋', name: '巴巴罗塞斯', no: 11 },
      { pos: '前锋', name: '麦考瓦特', no: 19 },
    ],
  },

  // ==================== H 组 ====================
  ESP: {
    fifaRank: 2, appearances: 17, best: '冠军（2010）',
    coach: '德拉富恩特',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },
  URU: {
    fifaRank: 14, appearances: 15, best: '冠军（1930、1950）',
    coach: '贝尔萨',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },
  CPV: {
    fifaRank: 65, appearances: 1, best: '首次参赛',
    coach: '布比斯塔',
    keyPlayer: '瑞安·门德斯（前锋）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '沃济尼亚', no: 1 },
      { pos: '后卫', name: '洛根·科斯塔', no: 4 },
      { pos: '后卫', name: '皮科·洛佩斯', no: 2 },
      { pos: '后卫', name: '史蒂文·莫雷拉', no: 15 },
      { pos: '中场', name: '雅米罗·蒙特罗', no: 10 },
      { pos: '中场', name: '凯文·皮纳', no: 8 },
      { pos: '中场', name: '德罗伊·杜阿尔特', no: 6 },
      { pos: '前锋', name: '瑞安·门德斯', no: 7 },
      { pos: '前锋', name: '加里·罗德里格斯', no: 11 },
      { pos: '前锋', name: '若瓦内·卡布拉尔', no: 9 },
      { pos: '前锋', name: '利夫拉门托', no: 19 },
    ],
  },
  KSA: {
    fifaRank: 54, appearances: 7, best: '16 强（1994）',
    coach: '曼奇尼',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },

  // ==================== I 组 ====================
  FRA: {
    fifaRank: 1, appearances: 17, best: '冠军（1998、2018）',
    coach: '德尚',
    keyPlayer: '姆巴佩（前锋）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '迈尼昂', no: 16 },
      { pos: '后卫', name: '孔德', no: 5 },
      { pos: '后卫', name: '萨利巴', no: 17 },
      { pos: '后卫', name: '于帕梅卡诺', no: 2 },
      { pos: '后卫', name: '特奥', no: 22 },
      { pos: '后卫', name: '科纳特', no: 24 },
      { pos: '中场', name: '楚阿梅尼', no: 8 },
      { pos: '中场', name: '坎特', no: 13 },
      { pos: '中场', name: '拉比奥', no: 14 },
      { pos: '前锋', name: '姆巴佩', no: 10 },
      { pos: '前锋', name: '登贝莱', no: 11 },
    ],
  },
  SEN: {
    fifaRank: 19, appearances: 4, best: '八强（2002）',
    coach: '西塞',
    keyPlayer: '马内（前锋）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '爱德华·门迪', no: 1 },
      { pos: '后卫', name: '库利巴利', no: 3 },
      { pos: '后卫', name: '尼亚凯特', no: 4 },
      { pos: '后卫', name: '雅各布斯', no: 2 },
      { pos: '后卫', name: '迪亚塔', no: 5 },
      { pos: '中场', name: '盖耶', no: 8 },
      { pos: '中场', name: '帕普·萨尔', no: 15 },
      { pos: '中场', name: '拉明·卡马拉', no: 6 },
      { pos: '前锋', name: '马内', no: 10 },
      { pos: '前锋', name: '尼古拉斯·杰克逊', no: 9 },
      { pos: '前锋', name: '伊斯梅拉·萨尔', no: 11 },
    ],
  },
  NOR: {
    fifaRank: 45, appearances: 4, best: '16 强（1998）',
    coach: '索尔巴肯',
    keyPlayer: '哈兰德（前锋）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '尼兰德', no: 1 },
      { pos: '后卫', name: '瑞尔森', no: 2 },
      { pos: '后卫', name: '阿耶尔', no: 4 },
      { pos: '后卫', name: '厄斯蒂高', no: 5 },
      { pos: '后卫', name: '沃尔夫', no: 3 },
      { pos: '中场', name: '厄德高', no: 10 },
      { pos: '中场', name: '贝格', no: 8 },
      { pos: '中场', name: '奥尔斯内斯', no: 6 },
      { pos: '前锋', name: '哈兰德', no: 9 },
      { pos: '前锋', name: '瑟洛特', no: 11 },
      { pos: '前锋', name: '努萨', no: 20 },
    ],
  },
  IRQ: {
    fifaRank: 68, appearances: 2, best: '小组赛',
    coach: '卡萨斯',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },

  // ==================== J 组 ====================
  ARG: {
    fifaRank: 4, appearances: 19, best: '冠军（1978、1986、2022）',
    coach: '斯卡洛尼',
    keyPlayer: '梅西（前锋）',
    squadConfirmed: false,
    squad: [],
  },
  AUT: {
    fifaRank: 25, appearances: 8, best: '季军（1954）',
    coach: '朗尼克',
    keyPlayer: '大卫·阿拉巴（后卫）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '彭茨', no: 1 },
      { pos: '后卫', name: '阿拉巴', no: 8 },
      { pos: '后卫', name: '林哈特', no: 5 },
      { pos: '后卫', name: '丹索', no: 4 },
      { pos: '后卫', name: '姆韦内', no: 2 },
      { pos: '中场', name: '萨比策', no: 9 },
      { pos: '中场', name: '鲍姆加特纳', no: 19 },
      { pos: '中场', name: '莱默', no: 20 },
      { pos: '中场', name: '楚克乌梅卡', no: 10 },
      { pos: '前锋', name: '阿瑙托维奇', no: 7 },
      { pos: '前锋', name: '格雷戈里奇', no: 11 },
    ],
  },
  ALG: {
    fifaRank: 38, appearances: 5, best: '16 强（2014）',
    coach: '佩特科维奇',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },
  JOR: {
    fifaRank: 70, appearances: 1, best: '首次参赛',
    coach: '阿穆塔',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },

  // ==================== K 组 ====================
  POR: {
    fifaRank: 8, appearances: 9, best: '季军（1966）',
    coach: '马丁内斯',
    keyPlayer: 'C罗（前锋）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '迪奥戈·科斯塔', no: 1 },
      { pos: '后卫', name: '鲁本·迪亚斯', no: 3 },
      { pos: '后卫', name: '努诺·门德斯', no: 19 },
      { pos: '后卫', name: '若昂·坎塞洛', no: 20 },
      { pos: '后卫', name: '达洛特', no: 2 },
      { pos: '中场', name: 'B费', no: 8 },
      { pos: '中场', name: 'B席', no: 10 },
      { pos: '中场', name: '维蒂尼亚', no: 23 },
      { pos: '前锋', name: 'C罗', no: 7 },
      { pos: '前锋', name: '拉斐尔·莱昂', no: 17 },
      { pos: '前锋', name: '贡萨洛·拉莫斯', no: 9 },
    ],
  },
  COL: {
    fifaRank: 10, appearances: 7, best: '八强（2014）',
    coach: '洛伦索',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },
  UZB: {
    fifaRank: 57, appearances: 1, best: '首次参赛',
    coach: '卡佩科',
    keyPlayer: '肖穆罗多夫（前锋）',
    squadConfirmed: false,
    squad: [],
  },
  COD: {
    fifaRank: 61, appearances: 2, best: '小组赛',
    coach: '德萨布雷',
    keyPlayer: '巴坎布（前锋）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '埃波罗', no: 1 },
      { pos: '后卫', name: '万-比萨卡', no: 2 },
      { pos: '后卫', name: '姆本巴', no: 4 },
      { pos: '后卫', name: '马苏阿库', no: 5 },
      { pos: '后卫', name: '阿克塞尔·图安泽贝', no: 6 },
      { pos: '中场', name: '卡库塔', no: 10 },
      { pos: '中场', name: '皮克尔', no: 8 },
      { pos: '中场', name: '邦贡达', no: 11 },
      { pos: '前锋', name: '巴坎布', no: 9 },
      { pos: '前锋', name: '维萨', no: 18 },
      { pos: '前锋', name: '马耶勒', no: 7 },
    ],
  },

  // ==================== L 组 ====================
  ENG: {
    fifaRank: 9, appearances: 17, best: '冠军（1966）',
    coach: '图赫尔',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },
  CRO: {
    fifaRank: 11, appearances: 7, best: '亚军（2018）',
    coach: '达利奇',
    keyPlayer: '莫德里奇（中场）',
    squadConfirmed: true,
    squad: [
      { pos: '门将', name: '利瓦科维奇', no: 1 },
      { pos: '后卫', name: '格瓦迪奥尔', no: 4 },
      { pos: '后卫', name: '斯塔尼希奇', no: 2 },
      { pos: '后卫', name: '舒塔洛', no: 5 },
      { pos: '中场', name: '莫德里奇', no: 10 },
      { pos: '中场', name: '科瓦契奇', no: 8 },
      { pos: '中场', name: '帕萨利奇', no: 15 },
      { pos: '中场', name: '苏契奇', no: 21 },
      { pos: '前锋', name: '佩里西奇', no: 4 },
      { pos: '前锋', name: '克拉马里奇', no: 9 },
      { pos: '前锋', name: '布迪米尔', no: 18 },
    ],
  },
  PAN: {
    fifaRank: 62, appearances: 2, best: '小组赛',
    coach: '克里斯蒂安森',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },
  GHA: {
    fifaRank: 59, appearances: 5, best: '八强（2010）',
    coach: '阿多',
    keyPlayer: '暂无数据',
    squadConfirmed: false,
    squad: [],
  },
};

module.exports = { teamDetails };
