"""add api_key_models

Revision ID: fa43d14845ee
Revises: 6c835882e158
Create Date: 2026-05-02 22:03:16.642081
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fa43d14845ee'
down_revision: Union[str, None] = '6c835882e158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_models',
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('api_key_id', 'model_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_key_models')
    # ### end Alembic commands ###
